### ISSUE TITLE
Question - There is no support for read uncommitted

### ISSUE THREAD

**Issue by carlosdorneles-mb** [Opus10/django-pgtransaction#7]
Hello, I was looking at the project code and I noticed that it doesn't have the `Read uncommitted` option. Is there any reason not to have this option in the project?

**Comment by PaulGilmartin** [comment]
@carlosdorneles-mb Thanks for your question. Whilst Postgres does officially allow one to set an isolation level of "READ UNCOMMITTED", its internal implementation is identical to that of READ COMMITTED. From the [docs](https://www.postgresql.org/docs/current/transaction-iso.html):

"In PostgreSQL, you can request any of the four standard transaction isolation levels, but internally only three distinct isolation levels are implemented, i.e., PostgreSQL's Read Uncommitted mode behaves like Read Committed. This is because it is the only sensible way to map the standard isolation levels to PostgreSQL's multiversion concurrency control architecture."

It is for that reason we exclude that isolation level explicitly, as otherwise it may lead to confusion. I believe Postgres only support it "superficially" to be in line with the SQL standard on isolation levels.
